### ISSUE TITLE
I cannot use "rebound.exe"

### ISSUE THREAD

**Issue by reaCodes** [shobrook/rebound#24]
OS: Windows 10
Python: 3.6.5

As the error in the picture shows, why is this?

![image](https://user-images.githubusercontent.com/13817254/38938978-6eba3822-4359-11e8-8e5f-1b62f3dd80af.png)

**Comment by y0umu** [comment]
I doubt if it ever runs if not in a POSIX environment #26

**Comment by reaCodes** [comment]
But I don't know what is POSIX environment, I am using Windows and "rebound.exe" has been added to the environment variable.

**Comment by shobrook** [comment]
Closing this since #26 is open.
