### ISSUE TITLE
Can't Found the packages which are already installed on Windows

### ISSUE THREAD

**Issue by virendrasuryavanshi** [shobrook/rebound#31]
Even though the packages are already installed it is giving errors that it requires this packages.

![issue](https://user-images.githubusercontent.com/24255721/39404688-a9941b2a-4bb5-11e8-821a-5ea376fdd0a0.PNG)

**Comment by shobrook** [comment]
Try using `pip3`. Also, if you're running `rebound` on Windows, it needs to be run in a UNIX-like environment, like Cygwin. See #26
