### ISSUE TITLE
can't use it in my CentOS machine

### ISSUE THREAD

**Issue by WillireamAngel** [shobrook/rebound#37]
```
[root@localhost whp]# rebound
bash: rebound: command not found...
[root@localhost whp]# rebound-cli
bash: rebound-cli: command not found..
[root@localhost whp]# rebound ./puppet.py
bash: rebound: command not found...
```

**Comment by shobrook** [comment]
Can you provide some more information? How did you install it?

**Comment by andrewfowlie** [comment]
same problem after installing on Ubuntu MATE 18 via pip3. The package was installed (i.e., python 3, import rebound was OK), but nothing was added to /usr/local/bin etc.
