### ISSUE TITLE
Opening results in browser doesn't support google chrome

### ISSUE THREAD

**Issue by MahmoudRizk** [shobrook/rebound#48]
On pressing <b>"B"</b> to browse the results while google chrome is the default browser, it just launch chrome with empty tab.

**Comment by akhilnambiar29** [comment]
Can you let me know you are facing this issue on which OS ? I just tried it on a mac with the default browser set as chrome , it works perfectly .

**Comment by MahmoudRizk** [comment]
Using Ubuntu 16.04.

**Comment by sanketsans** [comment]
I just tried it with ubuntu 18 with chrome set as my default browser. It opens the browser on pressing B. It is also working fine with firefox as well.

**Comment by shobrook** [comment]
Going to assume this isn't an issue with `rebound` if it works on Ubuntu 18.
