### ISSUE TITLE
rebound command not available from the command line

### ISSUE THREAD

**Issue by mjfuuu** [shobrook/rebound#55]
I tried installing rebound by following the instructions in the readme as well as variations I compiled from looking online.  After all of these I was unable to call "rebound" from the command line on a linux machine.

I tried the following installation commands:
pip install rebound-cli
pip3 install rebound-cli (with and without --user)
sudo apt-get install rebound-cli
git clone repo followed by python3 setup.py install (with and without --user)
I verified that pip and urwid are up to date.

After all of this I get the 'rebound: Command not found.' error no matter where in the directory i try to run it from

**Comment by Adarsh-Shrivastava-001** [comment]
On which OS are you working??

**Comment by sanilborkar** [comment]
I had the same issue. So I used a ```virtualenv``` for installation. It worked fine after that.

**Comment by shobrook** [comment]
Using a virtual environment should solve this issue. You can also try adding the `rebound` executable to your `$PATH`.
