### ISSUE TITLE
from queue import Queue: No module named queue (macOS)

### ISSUE THREAD

**Issue by pranavhari2** [shobrook/rebound#74]
![Screenshot 2020-05-01 at 7 51 00 PM](https://user-images.githubusercontent.com/42246450/80849438-21428280-8be5-11ea-979e-28aa28097d2b.png)

**Comment by leon332157** [comment]
Not sure but I don’t think Python 2 has a stand-alone queue module like Python 3, and since Python 2 has officially reached end of life, you should use Python 3 instead. It’s also stated in the read me that Python 3 is required.

**Comment by pranavhari2** [comment]
Didnt notice I was using 2.7, my fault.
