### ISSUE TITLE
New Features for Rebound

### ISSUE THREAD

**Issue by KelvinCT-12** [shobrook/rebound#81]
Hi

would like to implements some new functions for the rebound which includes:
- view the answer through GUI terminal 
- able to direct the user to the browser immediately to look for the link and answers
- able to record down and put it into the history

let me know what you guys think.

thank you

**Comment by shobrook** [comment]
The first two features already exist. You can view answers in the terminal (that's kind of the whole point), and you can open a search result in the browser by pressing `B`. 

For the third feature, if you're suggesting a "bookmark" feature then I don't think that's a good idea. It's overkill.
